baseURL = "http://martin.treml.codes/"
languageCode = "en-us"
theme = "munsio"
enableRobotsTXT = true
PygmentsCodeFences = true
PygmentsUseClasses = true

[params]

	title = "Martin Treml"
	subtitle = "Web Development, Golang, Docker and Electronics"
	copyright = "made with <i class='fa fa-fw fa-heart'></i> mostly on <i class='fa fa-fw fa-linux'></i>"

	metaTitle = "Martin Treml - Web Developer, Golang and Docker Fanboy"

	Author = "Martin Treml"

	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = "UA-112493737-1"

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Martin Treml"
	bio = "Ahoi! I'm an Web Developer working at <a href='https://www.karriere.at' target='_blank'>karriere.at</a>. I love tinkering with golang and docker and my newest hobby is all about electronics."
	#description = "Your description of the blog"
	#location = "" # optional
	twitter = "munsio" # optional
	github = "munsio" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs. 
	comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"


