baseURL = "http://munsio.causticlab.codes/"
languageCode = "en-us"
title = "Munsio"
theme = "munsio"
enableRobotsTXT = true
PygmentsCodeFences = true
PygmentsUseClasses = true

[params]

	title = "Tech thoughts"
	subtitle = "Docker, webdev and electronics"
	copyright = ""

	Author = "Martin Treml"

	# You can choose between green, orange, red and blue.
	themeColor = "purple"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = ""

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Martin Treml"
	bio = "I'm just a theme. That's it. If you like my design clone [me](//github.com/digitalcraftsman/hugo-steam-theme) from Github. Thanks."
	#description = "Your description of the blog"
	#location = "" # optional
	twitter = "munsio" # optional
	github = "munsio" # optional
 	gitlab = "" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs. 
	comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"


