[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.127.0"
GO_VERSION = "1.22.x"

[[redirects]]
from = "https://treml.dev/*"
to = "https://martin.treml.dev/:splat"
force = true
